### PR TITLE
WIP Process files in order

### PR DESCRIPTION
**Pull request by MiguelRocha**
This PR improves the speed of zimdump tool by processing the clusters in order optimizing the cluster cache utilization and avoiding unnecessary decompress operations.

### CODE REVIEW

**Comment by mgautierfr** [comment]
There is nothing to say on the code.

However, sorting the article per cluster would be better done in libzim (https://github.com/openzim/libzim/issues/300).

**Comment by kelson42** [comment]
@MiguelRocha What should we do with this PR?

**Comment by MiguelRocha** [comment]
@kelson42 @mgautierfr I've been doing some performance tests with this and I found that this PR does not introduce a significant performance advantage on my machine. 

We use a caching mechanism that is blocking a lot of threads and therefore it is very hard to take advantage of the multiple CPUs.

I have a couple of them in mind but I don't want to spend a lot of time on it so we maybe we can close this PR. What do you think?

**Comment by kelson42** [comment]
We need to change a few things in the libzim itself (in particular the cache system) to be able to have at the multhreading bringing a lot. Closing this PR for the moment.

**Pull request closed without merging**
