### PR TITLE
Add -J (--threads) option to zimrecreate tool

### PR DESCRIPTION
**Pull request by data-man**

### CODE REVIEW

**Comment by kelson42** [comment]
@data-man still a draft?

**Comment by data-man** [comment]
@kelson42 I was just waiting for some feedback. :)

**Comment by kelson42** [comment]
@data-man OK, please fix the PR, always rebase on master in place of merging master in feature branch. I will assign @mgautierfr for a review.

**Comment by data-man** [comment]
If there are no other issues, could it be merged?
In my next PR i'll use docopt, so CodeFactor's issue will dissapear.

**Comment by kelson42** [comment]
@data-man Thx, we just need to wait @mgautierfr's review.

**Review by mgautierfr — APPROVED** [review]

**Comment by mgautierfr** [comment]
Nothing to say. Thanks

**Pull request merged**
