### PR TITLE
Fix compilation against latest libzim

### LINKED ISSUE #259: zim-tools does not compile anymore
```
[8/45] Compiling C++ object 'src/25a6634@@zimsearch@exe/zimsearch.cpp.o'.
FAILED: src/25a6634@@zimsearch@exe/zimsearch.cpp.o 
ccache c++ -Isrc/25a6634@@zimsearch@exe -Isrc -I../src -I/usr/local/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Werror -std=c++11 -g -Werror -Wall '-DVERSION="2.2.0"' -MD -MQ 'src/25a6634@@zimsearch@exe/zimsearch.cpp.o' -MF 'src/25a6634@@zimsearch@exe/zimsearch.cpp.o.d' -o 'src/25a6634@@zimsearch@exe/zimsearch.cpp.o' -c ../src/zimsearch.cpp
../src/zimsearch.cpp: In function ‘int main(int, char**)’:
../src/zimsearch.cpp:68:28: error: no matching function for call to ‘zim::Query::setQuery(std::string&, bool)’
   68 |     query.setQuery(s, false);
      |                            ^
In file included from ../src/zimsearch.cpp:21:
/usr/local/include/zim/search.h:129:12: note: candidate: ‘zim::Query& zim::Query::setQuery(const string&)’
  129 |     Query& setQuery(const std::string& query);
      |            ^~~~~~~~
/usr/local/include/zim/search.h:129:12: note:   candidate expects 1 argument, 2 provided
[17/45] Compiling C++ object 'src/zimcheck/09b87c9@@zimcheck@exe/checks.cpp.o'.
ninja: build stopped: subcommand failed.
```

Against latest dev libzim

### PR DESCRIPTION
**Pull request by maneeshpm**
fixes #259

### CODE REVIEW

**Comment by maneeshpm** [comment]
@kelson42 @mgautierfr any idea why the zimwriterfs unit test fails?

**Comment by kelson42** [comment]
@maneeshpm no

**Comment by mgautierfr** [comment]
No idea. Does the test also fail of your side ?

**Comment by maneeshpm** [comment]
@mgautierfr Yeah, its failing locally as well

**Comment by mgautierfr** [comment]
So it will be easy to know the problem. A debugger is your friend here :)

**Comment by kelson42** [comment]
@maneeshpm Any news here, have you been able to identify the problem?

**Comment by maneeshpm** [comment]
@kelson42 For some reason, this test is giving a segmentation fault
https://github.com/openzim/zim-tools/blob/master/test/zimwriterfs-zimcreatorfs.cpp#L124-L129

**Comment by maneeshpm** [comment]
@mgautierfr @kelson42 This error is caused by the changes introduced in openzim/libzim#603, How is it related?

**Comment by kelson42** [comment]
@might that be that zimwriterfs tries manually to delete a temporary data? Does the zimwriterfs crashes? Or just returns 1? Where is that failing, at which line?

**Comment by maneeshpm** [comment]
@kelson42 The segmentation fault is encountered after the statement `ZimCreateFS zimCreate("some path")` (line 127) is run. Since we are getting a segmentation fault **after** the statement is run, I think you are right. Issue might be in the destructor.

**Comment by kelson42** [comment]
@maneeshpm Are you sure the dicotry used for this test is empty? Maybe there is something left from a previous run?

**Comment by maneeshpm** [comment]
@kelson42 Yes I checked, the directory is empty already. And if it should be already empty in CI since it is made from scratch.

**Comment by mgautierfr** [comment]
I will have a look. It seems that the bug was introduce from one of my PR.

**Comment by mgautierfr** [comment]
The test is fixed by #613.

**Comment by kelson42** [comment]
@mgautierfr Would you be able please to approve this PR?

**Comment by kelson42** [comment]
PR is too simple, merging myself.

**Pull request merged**
