### PR TITLE
Fixes #171 zimdump list --ns=<N> doesn't work as a filter

### LINKED ISSUE #171: zimdump list --ns=<N> doesn't work as a filter
Program: zimdump (for zim-tools)
Version: current master (243e869)

## Actual result:

The output of those commands below are equal:

```
$ ~/oz/zim-tools/build/src/zimdump list ~/oz/ZIM.files/storybox_en_2020-05.zim | wc -l
591

$ ~/oz/zim-tools/build/src/zimdump list --ns=M ~/oz/ZIM.files/storybox_en_2020-05.zim | wc -l
591
```

## Expected result:

```
$ ~/oz/zim-tools/build/src/zimdump list --ns=M ~/oz/ZIM.files/storybox_en_2020-05.zim
Counter
Creator
Date
Description
Flavour
Language
Name
Publisher
Scraper
Source
Tags
Title
```

I expect --ns=<N> to work as a filter, listing entries only from the specified namespace, skipping the others.

### PR DESCRIPTION
**Pull request by maneeshpm**
Adding a function `listEntriesByNamespace()`

### CODE REVIEW

**Comment by maneeshpm** [comment]
@veloman-yunkan a neat workaround is to return `(namespace, "")` in the `parseLongPath()` function when the path contains only one valid namespace character, like
```c++
std::tuple<char, std::string> zim::parseLongPath(const std::string& longPath)
{
  /* Index of the namespace char; discard '/' from absolute paths */
  const unsigned int i = (longPath[0] == '/') ? 1 : 0;
  if (i + 2 >= longPath.size() && longPath[i] != '/') 
    return std::make_tuple(longPath[i], "");
  if (i + 2 >= longPath.size() || longPath[i] == '/' || longPath[i+1] != '/')
    throw std::runtime_error("Cannot parse path");
```
This change does result in the proper behavior
```
$ zimdump list --ns=M khan-academy-videos_fr_amine_2020-06.zim                                                                                             
M/Counter
M/Creator
M/Date
M/Description
M/Flavour
M/Language
M/Name
M/Publisher
M/Scraper
M/Tags
M/Title
```
Is there any other way to access the `findx(ns, path)` function bypassing the `parseLongPath()`?

**Comment by maneeshpm** [comment]
@veloman-yunkan Since directly using `zim::archive::findByPath()` was not possible, changed the function `listEntriesByNamespace()` to a brute force over all possible first characters for the path (since URL=/namespace/path).

**Review by veloman-yunkan — CHANGES_REQUESTED** [review]
The brute force approach isn't brute enough - it considers only paths starting with an ASCII alphanumeric character. But we shouldn't pursue the brute force approach at all. Instead `findByPath()->findx()->parseLongPath()` must be fixed in `libzim`. Please open a ticket in libzim, fix that one and then drop the last two commits from this PR.

**Comment by maneeshpm** [comment]
@veloman-yunkan openzim/libzim#479 as it is cannot fix this issue because
```c++
Archive::EntryRange<EntryOrder::pathOrder> Archive::findByPath(std::string path) const
  {
    entry_index_t begin_idx, end_idx;
    if (m_impl->hasNewNamespaceScheme()) {
     ...
    } else {
      begin_idx = m_impl->findx(path).second;
      path.back()++;
      end_idx = m_impl->findx(path).second;
    }
    return Archive::EntryRange<EntryOrder::pathOrder>(m_impl, begin_idx.v, end_idx.v);
  }
```
if I pass a valid namespace `"J"` to `findByPath`, begin_idx will be assigned properly, but end_idx will break since path.back()++ makes path = `"K"` which is not a valid namespace character and `parseLongPath` will throw an error.

**Comment by kelson42** [comment]
@maneeshpm What is the status here now that you have fixed the libzim?

**Comment by maneeshpm** [comment]
@kelson42 The fix is working as expected. openzim/libzim#479 completes this fix.

**Comment by kelson42** [comment]
@veloman-yunkan If I understand properly this PR needs your review and formal approval.

**Review by veloman-yunkan — APPROVED** [review]

**Comment by kelson42** [comment]
@maneeshpm Thank you for the good work on this bug. Share your email address with me (kelson @kiwix.org) if you want to get invitation to join us on Slack.

**Comment by maneeshpm** [comment]
I would really appreciate it, thanks @kelson42. Dropping you a mail.

**Pull request merged**
